# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24b05ce5f06e2b74638892bfe838ba41146078e3fa303f9fe159af69abeaf937f0f96f33907d57008850dd7bc7198ed9e2eb6818fa758343f4728aab79284cac

test:
  secret_key_base: f22c30f863825e906d0ca44c6f44e82d320f0d813bcd6ba9582b57d4955a7d3b87f745de4971614ca0ec099e4acf9ae5a22a163e6fa6c63e4482e5225dea62f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
